import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gym/features/gym_owner/data/repositories/gym_owner_repository.dart';
import 'package:gym/features/gym_owner/domain/models/attendance_model.dart';
import 'package:gym/features/gym_owner/domain/models/member_model.dart';
import 'package:gym/features/gym_owner/domain/models/payment_model.dart';

class MemberCardWidget extends ConsumerWidget {
  final MemberModel member;
  final List<AttendanceModel> attendances;
  final VoidCallback? onTap;

  const MemberCardWidget({
    super.key,
    required this.member,
    required this.attendances,
    this.onTap,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final dueAmount = (member.monthlyPlanAmount ?? 0) - (member.paidAmount ?? 0);
    
    final memberAttendances = attendances.where((a) => a.memberId == member.id);
    final memberAttendance = memberAttendances.isNotEmpty ? memberAttendances.last : null;
    
    String attendanceLabel = 'Check In';
    IconData attendanceIcon = Icons.login;
    Color attendanceColor = Colors.blue;
    bool isAttendanceDisabled = false;

    if (memberAttendance != null) {
      if (memberAttendance.checkOutTime == null) {
        attendanceLabel = 'Check Out';
        attendanceIcon = Icons.logout;
        attendanceColor = Colors.orange;
      } else {
        attendanceLabel = 'Completed';
        attendanceIcon = Icons.check_circle;
        attendanceColor = Colors.grey;
        isAttendanceDisabled = true;
      }
    }

    return Card(
      elevation: 2,
      margin: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 8.0),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(12.0),
          child: Column(
            children: [
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  CircleAvatar(
                    radius: 30,
                    backgroundImage: member.profilePhotoUrl != null && member.profilePhotoUrl!.isNotEmpty
                        ? NetworkImage(member.profilePhotoUrl!)
                        : null,
                    child: member.profilePhotoUrl == null || member.profilePhotoUrl!.isEmpty
                        ? const Icon(Icons.person, size: 30)
                        : null,
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          member.name,
                          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.bold,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                        const SizedBox(height: 4),
                        Text('ID: ${member.memberId ?? member.id}'),
                        const SizedBox(height: 4),
                        Text('Plan: ${member.membershipType ?? 'N/A'}'),
                        const SizedBox(height: 4),
                        Text(
                          'Expires: ${member.expiryDate?.toString().split(' ')[0] ?? 'N/A'}',
                          style: TextStyle(
                            color: member.isMembershipActive ? Colors.green : Colors.red,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'Due: \$${(dueAmount > 0 ? dueAmount : 0).toStringAsFixed(2)}',
                          style: TextStyle(
                            color: dueAmount > 0 ? Colors.red : Colors.green,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const Divider(height: 24),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  TextButton.icon(
                    onPressed: isAttendanceDisabled ? null : () async {
                      try {
                        final repo = ref.read(gymOwnerRepositoryProvider);
                        if (memberAttendance == null) {
                          // Check in
                          final now = DateTime.now();
                          final newAttendance = AttendanceModel(
                            id: '', // Will be generated by Firestore
                            gymId: member.gymId,
                            memberId: member.id,
                            date: DateTime(now.year, now.month, now.day),
                            checkInTime: now,
                          );
                          await repo.checkIn(newAttendance);
                          if (context.mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Checked In successfully')),
                            );
                          }
                        } else if (memberAttendance.checkOutTime == null) {
                          // Check out
                          await repo.checkOut(memberAttendance.id, DateTime.now());
                          if (context.mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Checked Out successfully')),
                            );
                          }
                        }
                      } catch (e) {
                        if (context.mounted) {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(content: Text('Error: $e')),
                          );
                        }
                      }
                    },
                    icon: Icon(attendanceIcon, color: attendanceColor),
                    label: Text(attendanceLabel, style: TextStyle(color: attendanceColor)),
                  ),
                  TextButton.icon(
                    onPressed: () {
                      showDialog(
                        context: context,
                        builder: (context) => _RenewPlanDialog(member: member),
                      );
                    },
                    icon: const Icon(Icons.autorenew, color: Colors.green),
                    label: const Text('Renew Plan'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _RenewPlanDialog extends ConsumerStatefulWidget {
  final MemberModel member;

  const _RenewPlanDialog({required this.member});

  @override
  ConsumerState<_RenewPlanDialog> createState() => _RenewPlanDialogState();
}

class _RenewPlanDialogState extends ConsumerState<_RenewPlanDialog> {
  String _paymentStatus = 'Pending';
  String _paymentMethod = 'Cash';
  final List<String> _paymentMethods = ['Cash', 'EasyPaisa', 'Jazz Cash', 'Bank Transfer'];
  bool _isLoading = false;

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Renew Plan'),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          DropdownButtonFormField<String>(
            decoration: const InputDecoration(labelText: 'Payment Status'),
            value: _paymentStatus,
            items: ['Pending', 'Received']
                .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                .toList(),
            onChanged: (val) {
              if (val != null) setState(() => _paymentStatus = val);
            },
          ),
          if (_paymentStatus == 'Received') ...[
            const SizedBox(height: 16),
            DropdownButtonFormField<String>(
              decoration: const InputDecoration(labelText: 'Payment Method'),
              value: _paymentMethod,
              items: _paymentMethods
                  .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                  .toList(),
              onChanged: (val) {
                if (val != null) setState(() => _paymentMethod = val);
              },
            ),
          ],
        ],
      ),
      actions: [
        TextButton(
          onPressed: _isLoading ? null : () => Navigator.pop(context),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _isLoading ? null : _submit,
          child: _isLoading 
            ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)) 
            : const Text('Renew'),
        ),
      ],
    );
  }

  Future<void> _submit() async {
    setState(() => _isLoading = true);
    try {
      final repo = ref.read(gymOwnerRepositoryProvider);
      final now = DateTime.now();
      
      // Calculate new expiry date (+30 days)
      DateTime newExpiry = widget.member.expiryDate ?? now;
      if (newExpiry.isBefore(now)) {
        newExpiry = now;
      }
      newExpiry = newExpiry.add(const Duration(days: 30));

      final planAmount = widget.member.monthlyPlanAmount ?? 0.0;
      double newPaidAmount = 0.0;
      
      if (_paymentStatus == 'Received') {
        newPaidAmount = planAmount;
        
        if (planAmount > 0) {
          final payment = PaymentModel(
            id: 'temp',
            gymId: widget.member.gymId,
            memberId: widget.member.id,
            amount: planAmount,
            paymentDate: now,
            paymentMethod: _paymentMethod,
            createdAt: now,
          );
          await repo.addPayment(payment);
        }
      }

      final updatedMember = MemberModel(
        id: widget.member.id,
        gymId: widget.member.gymId,
        name: widget.member.name,
        phone: widget.member.phone,
        email: widget.member.email,
        membershipType: widget.member.membershipType,
        startDate: widget.member.startDate,
        expiryDate: newExpiry,
        trainerId: widget.member.trainerId,
        isActive: widget.member.isActive,
        createdAt: widget.member.createdAt,
        profilePhotoUrl: widget.member.profilePhotoUrl,
        gender: widget.member.gender,
        memberId: widget.member.memberId,
        monthlyPlanAmount: widget.member.monthlyPlanAmount,
        paymentDate: now,
        paidAmount: newPaidAmount,
        paymentMethod: _paymentStatus == 'Received' ? _paymentMethod : widget.member.paymentMethod,
        admissionFee: widget.member.admissionFee,
        dateOfBirth: widget.member.dateOfBirth,
        address: widget.member.address,
        isDeleted: widget.member.isDeleted,
        deletedAt: widget.member.deletedAt,
      );

      await repo.updateMember(updatedMember);
      
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Plan renewed successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }
}
