import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gym/features/gym_owner/domain/models/member_model.dart';
import 'package:gym/features/gym_owner/domain/models/workout_model.dart';

final memberRepositoryProvider = Provider<MemberRepository>((ref) {
  return MemberRepository(FirebaseFirestore.instance);
});

class MemberRepository {
  final FirebaseFirestore _firestore;

  MemberRepository(this._firestore);

  // Get My Membership Details
  Stream<MemberModel?> getMyDetails(String memberId) {
    return _firestore.collection('members').doc(memberId).snapshots().map((doc) {
      if (!doc.exists || doc.data() == null) return null;
      return MemberModel.fromMap(doc.data()!, doc.id);
    });
  }

  // Get My Assigned Workouts
  Stream<List<WorkoutModel>> getMyWorkouts(String memberId) {
    return _firestore
        .collection('workouts')
        .where('memberId', isEqualTo: memberId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => WorkoutModel.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Add a progress photo (The URL would be generated by Firebase Storage)
  Future<void> addProgressPhoto({
    required String gymId,
    required String memberId,
    required String imageUrl,
    required double weight,
  }) async {
    await _firestore.collection('progress').add({
      'gymId': gymId,
      'memberId': memberId,
      'imageUrl': imageUrl,
      'weight': weight,
      'uploadDate': FieldValue.serverTimestamp(),
    });
  }
}
