// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWjFNmNFw1KoJFCN-vhlv6CW5c0Gx-Ks',
    appId: '1:387079868423:web:11493ecf26e2286a939aa2',
    messagingSenderId: '387079868423',
    projectId: 'gymhisabkitab',
    authDomain: 'gymhisabkitab.firebaseapp.com',
    storageBucket: 'gymhisabkitab.firebasestorage.app',
    measurementId: 'G-BHY66B1M37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFile3W40YHS_5rIn5rFus3nf4kgTNi40',
    appId: '1:387079868423:android:535c70cc299f8e34939aa2',
    messagingSenderId: '387079868423',
    projectId: 'gymhisabkitab',
    storageBucket: 'gymhisabkitab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfs9RP39i8S5lVX3sw8zNQpq1n1LHhs1E',
    appId: '1:387079868423:ios:27743f6ef9660dd0939aa2',
    messagingSenderId: '387079868423',
    projectId: 'gymhisabkitab',
    storageBucket: 'gymhisabkitab.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfs9RP39i8S5lVX3sw8zNQpq1n1LHhs1E',
    appId: '1:387079868423:ios:27743f6ef9660dd0939aa2',
    messagingSenderId: '387079868423',
    projectId: 'gymhisabkitab',
    storageBucket: 'gymhisabkitab.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAWjFNmNFw1KoJFCN-vhlv6CW5c0Gx-Ks',
    appId: '1:387079868423:web:7042a441bb2d373c939aa2',
    messagingSenderId: '387079868423',
    projectId: 'gymhisabkitab',
    authDomain: 'gymhisabkitab.firebaseapp.com',
    storageBucket: 'gymhisabkitab.firebasestorage.app',
    measurementId: 'G-GHJWSB3RMP',
  );
}
